### PR TITLE
Fix double /reset in agent mode

### LINKED ISSUE #5487: [FEAT]: Fix double /reset in agent mode
### What would you like to see?

Currently, when in an agent session and the user types `/reset` this will exit the agent session, but another `/reset` is required to clear the chat.

One `/reset` should clear the page as well as kill the agent session (if one is underway).

### PR DESCRIPTION
**Pull request by shatfield4**
### Pull Request Type

- [ ] ✨ feat (New feature)
- [x] 🐛 fix (Bug fix)
- [ ] ♻️ refactor (Code refactoring without changing behavior)
- [ ] 💄 style (UI style changes)
- [ ] 🔨 chore (Build, CI, maintenance)
- [ ] 📝 docs (Documentation updates)

### Relevant Issues

resolves #5487 

### Description

- `/reset` in an active agent session now ends the agent and clears the chat in a single action (previously required two `/resets`)
- Handles edge case where in-flight responses would reappear after `/reset` once backend finished responding to message
- Simplified slash command menu to only show `/reset` (removed `/exit` from this menu since we now default all chats to agent mode but is still available to use for power users. Agent thinking block on startup still tells user to use `/exit` to exit agent session)

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated (if applicable)
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

**Review by angelplusultra — APPROVED** [review]
LGTM

File: server/utils/agents/aibitat/plugins/chat-history.js [hunk 1]
```diff
@@ -12,6 +12,12 @@ const chatHistory = {
     return {
       name: this.name,
       setup: function (aibitat) {
+        // If the agent is aborted (e.g. user sent /reset mid-response), skip
+        // the pending save so a completing in-flight response doesn't reappear.
+        aibitat.onAbort(() => {
+          aibitat._aborted = true;
+        });
```
Comment (timothycarambat) [inline server/utils/agents/aibitat/plugins/chat-history.js:19]: @shatfield4 This just saved us a ton of trouble potentially - will sync on slack

**Review by timothycarambat — APPROVED** [review]
