### PR TITLE
fix: invalid docs links in FileSystemSkillPanel

### LINKED ISSUE #5517: Invalid docs links in FileSystemSkillPanel (agents settings)
### Where

`frontend/src/pages/Admin/Agents/FileSystemSkillPanel/index.jsx`
- Line 191 (the "Learn more" link under the description)
- Line 278 (the `<Trans>` link inside `WarningBanner`)

### What's wrong

Both use:

```jsx
<Link to="/docs/guides/agent-skills/filesystem-agent" target="_blank" />
```

This is broken in two ways:

1. **Wrong URL shape.** It's a relative SPA path via react-router's `<Link>`, so clicking it tries to navigate inside the app to `/docs/guides/agent-skills/filesystem-agent` — a route that doesn't exist. Every other docs link in the codebase points at the external site, e.g. `https://docs.anythingllm.com/agent/custom/developer-guide`, `https://docs.anythingllm.com/mcp-compatibility/overview`, `https://docs.anythingllm.com/agent-flows/overview`, etc.
2. **Route doesn't exist on the docs site either.** `docs.anythingllm.com` doesn't have a `/docs/guides/agent-skills/filesystem-agent` page, so even rewriting to an absolute URL would 404 until the correct docs path is confirmed (or the docs page is created).

Additionally, external docs links in the rest of the app use `<a href="https://...">`, not `<Link to=...>` — the router `<Link>` is not appropriate for an off-app URL.

### Expected

- Replace both occurrences with an `<a href="https://docs.anythingllm.com/...">` pointing at the actual filesystem-agent docs page (path to be confirmed by whoever authored the filesystem skill).
- If no docs page exists yet, either create it or remove the link until one does.

### Repro

1. Open Admin → Agent Skills → enable/open the Filesystem skill panel.
2. Click "Learn more →" or the link inside the orange warning banner.
3. Observe the app navigates internally to a non-existent `/docs/...` route instead of opening the docs site.

### PR DESCRIPTION
**Pull request by angelplusultra**
### Pull Request Type

- [ ] ✨ feat (New feature)
- [x] 🐛 fix (Bug fix)
- [ ] ♻️ refactor (Code refactoring without changing behavior)
- [ ] 💄 style (UI style changes)
- [ ] 🔨 chore (Build, CI, maintenance)
- [ ] 📝 docs (Documentation updates)

### Relevant Issues

resolves #5517

### Description

The "Learn more" link and the link inside the warning banner on the Filesystem agent skill panel (`frontend/src/pages/Admin/Agents/FileSystemSkillPanel/index.jsx`) were broken in two ways:

1. They used react-router's `<Link to="/docs/guides/agent-skills/filesystem-agent" />`, which is a relative SPA path and caused the app to navigate internally to a non-existent route instead of opening the docs site.
2. The underlying path didn't exist on the docs site either.

This PR:

- Replaces both `<Link to=...>` usages with plain `<a href="https://docs.useanything.com/agent/usage/file-system-agent">` anchors.
- Adds `target="_blank"` + `rel="noopener noreferrer"` to match the external-link convention already used in the sibling `Admin/Agents/MCPServers/index.jsx` (also mitigates reverse-tabnabbing / referrer leakage).
- Drops the now-unused `Link` import from `react-router-dom`.

### Visuals (if applicable)

N/A — visual output is unchanged; only the link target/behavior was fixed.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [ ] Relevant documentation has been updated (if applicable)
- [x] I have tested my code functionality
- [ ] Docker build succeeds locally

### CODE REVIEW

File: frontend/src/pages/Admin/Agents/FileSystemSkillPanel/index.jsx [hunk 1]
```diff
@@ -274,9 +274,10 @@ function WarningBanner() {
           i18nKey="agent.skill.filesystem.warning"
           components={{
             link: (
-              <Link
-                to="/docs/guides/agent-skills/filesystem-agent"
```
Comment (timothycarambat) [inline frontend/src/pages/Admin/Agents/FileSystemSkillPanel/index.jsx:278]: Use https://github.com/Mintplex-Labs/anything-llm/blob/master/frontend/src/utils/paths.js#L55-L57 instead.

Keep this as a `Link`

**Review by timothycarambat — CHANGES_REQUESTED** [review]

File: frontend/src/pages/Admin/Agents/FileSystemSkillPanel/index.jsx [hunk 2]
```diff
@@ -274,9 +274,10 @@ function WarningBanner() {
...
+              <a
```
Comment (timothycarambat) [inline frontend/src/pages/Admin/Agents/FileSystemSkillPanel/index.jsx]: This also still does not render?

**Review by timothycarambat — CHANGES_REQUESTED** [review]
