### PR TITLE
fix: long-prompt bubble flicker & See More collapse on streaming/scroll

### LINKED ISSUE #5455: [BUG]: Intense UI flickering upon sending large mesages
### How are you running AnythingLLM?

Docker (remote machine)

### What happened?

After sending a prompt long enough to trigger the see more option on the prompt's chat buble, the UI starts flickering. When the LLM starts writing the output message the flickering intensifies significantly.

I expected the UI not to flicker.

### Are there known steps to reproduce?

Send a prompt that triggers the see more text on the user's text buble. After ollama loads the LLM and it starts thinking the flickering starts. It intensifies significantly when the LLM starts to actually output its answer.

I am running AnythingLLM on a personal computer and exposing it to my tailnet for remote access. The UI is being opened on a mobile Firefox window of a samsung galaxy Tab S9.

This issue has happend to me with or without the phisical keyboard, in landscape and portrait mode, with splitscreen and without splitscreen, on full screen and DEX. I have been unable to find a configuration where it doesn't happen.

I have a screen recording but github did not allow me to upload the .mp4 file. I am willing to send the video through other meens if requested.

### LLM Provider & Model (if applicable)

Ollama / Gemma-4-26b-a4b

### Embedder Provider & Model (if applicable)

Anything LLM / all-MiniLM-L6-v2

### PR DESCRIPTION
**Pull request by angelplusultra**
### Pull Request Type

- [x] 🐛 fix (Bug fix)

### Relevant Issues

resolves #5455

### Description

Fixes two related bugs with the \"See More\" collapse bubble on long user prompts in the chat UI:

1. **Flicker during streaming** — When a long prompt is collapsed (above the 250px threshold) and a new response is streaming out, the bubble briefly flashes its full content, then re-collapses. Visible as a jarring flicker near the end of every stream.
2. **\"See More\" re-collapses on scroll / unrelated re-renders** — After clicking \"See More\" to expand a long prompt, the bubble collapses itself again while reading/scrolling.

**Root cause (both bugs):** `HistoricalMessage` used `uuid = v4()` as a default parameter. User messages are pushed to history without a uuid (`ChatContainer/index.jsx`) and the server's `convertToChatHistory` also omits it (`server/utils/helpers/chat/responses.js`). Default params run on every call, so `v4()` generated a fresh uuid on every re-render. That uuid is used as `key={uuid}` on the wrapper `<div>` — when React sees a new key it unmounts and remounts the subtree, wiping `TruncatableContent`'s `isExpanded` / `isOverflowing` state.

- The \"flicker at end of stream\" triggers when `finalizeResponseStream` backfills the user message's `chatId` (`utils/chat/index.js:107`). The memo comparison flips on `chatId`, re-render fires, uuid regenerates, subtree remounts.
- The \"re-collapse on scroll\" is the same mechanism — any memo miss remounts and resets `isExpanded`.

**Fix** in `frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx`:

1. Freeze uuid on first render via `useState(() => uuidProp ?? v4())` so it stays stable across re-renders and the wrapper div's `key` never changes.
2. Swap `useEffect` → `useLayoutEffect` for the `scrollHeight` measurement in `TruncatableContent` so the collapse applies before the first paint, eliminating a one-frame flash of uncollapsed content on mount.

### Visuals (if applicable)

N/A — fix removes a visual flicker.

### Additional Information

Small, scoped change to one file (9 insertions, 3 deletions). Behavior for assistant messages is unchanged since they always arrive with a uuid.

### Developer Validations

- [x] I ran \`yarn lint\` from the root of the repo & committed changes
- [ ] Relevant documentation has been updated (if applicable)
- [x] I have tested my code functionality
- [ ] Docker build succeeds locally

### CODE REVIEW

File: frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx [hunk 1]
```diff
@@ -38,6 +38,10 @@ const HistoricalMessage = ({
   metrics = {},
   outputs = [],
 }) => {
+  // Freeze uuid on first render. User messages arrive without a uuid and this value
+  // is used as the wrapper div's `key` — a default param fallback would regenerate
+  // on every render and remount the subtree, wiping TruncatableContent state.
+  const [uuid] = useState(() => uuidProp ?? v4());
```
Comment (shatfield4) [inline frontend/src/components/WorkspaceChat/ChatContainer/ChatHistory/HistoricalMessage/index.jsx:44]: 👍

**Review by shatfield4 — APPROVED** [review]
LGTM
