### PR TITLE
fix: omit temperature param for Bedrock Claude Opus 4.7

### LINKED ISSUE #5461: [BUG]: Temperature deprecated on Claude Opus 4.7
### How are you running AnythingLLM?

AnythingLLM desktop app

### What happened?

I'm using AWS Bedrock and I want to migrate to Claude Opus 4.7. I've configured the model in the "LLM Preferences" tab and I'm getting this error : 

`AWSBedrock::streamGetChatCompletion failed during setup. The model returned the following errors: {"type":"error","request_id":"req_nd3rf2fu2rzszuywalosdulhkzz7pvbzz4lju5q7nfec4ciuvb4a","error":{"type":"invalid_request_error","message":"`temperature` is deprecated for this model."}}`

Would it be possible to disable the temperature ?

### Are there known steps to reproduce?

1. Use AWS Bedrock and have the correct credentials
2. Enter the model ID (anthropic.claude-opus-4-7)
3. Send a message

### LLM Provider & Model (if applicable)

AWS Bedrock / anthropic.claude-opus-4-7

### Embedder Provider & Model (if applicable)

/

### PR DESCRIPTION
**Pull request by angelplusultra**
### Pull Request Type

- [ ] ✨ feat (New feature)
- [x] 🐛 fix (Bug fix)
- [ ] ♻️ refactor (Code refactoring without changing behavior)
- [ ] 💄 style (UI style changes)
- [ ] 🔨 chore (Build, CI, maintenance)
- [ ] 📝 docs (Documentation updates)

### Relevant Issues

resolves #5461

### Description

AWS Bedrock rejects requests to `anthropic.claude-opus-4-7` when `temperature` is included in `inferenceConfig` — the parameter is deprecated for that model and the call fails validation.

This PR introduces a module-level `MODELS_THAT_REJECT_TEMPERATURE` list in `server/utils/AiProviders/bedrock/index.js` and conditionally omits `temperature` from the Converse API payload in both call sites that build it:

- `getChatCompletion` (non-streaming)
- `streamGetChatCompletion` (streaming)

All other Bedrock models continue to receive `temperature ?? this.defaultTemp` exactly as before, so behavior is unchanged outside of the explicitly listed models. The agent-mode Bedrock provider (`server/utils/agents/aibitat/providers/bedrock.js`) never sent `temperature` in the first place, so no changes were needed there.

### Visuals (if applicable)

N/A

### Additional Information

If Bedrock later adds other models that reject `temperature`, extend the `MODELS_THAT_REJECT_TEMPERATURE` array at the top of `bedrock/index.js` — no other code changes required.

### Developer Validations

- [x] I ran \`yarn lint\` from the root of the repo & committed changes
- [x] Relevant documentation has been updated (if applicable)
- [ ] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

File: server/utils/AiProviders/bedrock/index.js [hunk 1]
```diff
@@ -21,6 +21,9 @@ const {
   getBedrockAuthMethod,
 } = require("./utils");
 
+// Bedrock models known to reject the `temperature` inference parameter.
+const MODELS_THAT_REJECT_TEMPERATURE = ["anthropic.claude-opus-4-7"];
```
Comment (timothycarambat) [inline server/utils/AiProviders/bedrock/index.js:25]: _commenting feedback on old commit as I already fixed this_

There is already an on-class prop for `noSystemPromptModels` - this same array should have operated the same way - no reason to hoist above the class here so at least it is consistent.

File: server/utils/AiProviders/bedrock/index.js [hunk 2]
```diff
@@ -408,7 +411,9 @@ class AWSBedrockLLM {
             messages: history,
             inferenceConfig: {
               maxTokens: maxTokensToSend,
-              temperature: temperature ?? this.defaultTemp,
+              ...(!MODELS_THAT_REJECT_TEMPERATURE.includes(this.model)
+                ? { temperature: temperature ?? this.defaultTemp }
+                : {}),
```
Comment (timothycarambat) [inline server/utils/AiProviders/bedrock/index.js:416]: _commenting feedback on old commit as I already fixed this_


This could have just been a method on the class to call and save on check/logic.
This currently logic does not compensate for something AWS does where there can be a prefix for the serverless version of a model where this would be `us.anthropic-xxxxx` where it puts `us` or the zone before the tag.

This is maybe a niche case, but would be messy without just doing a class method that we can apply in a single function and apply to both methods here.
