### PR TITLE
Refine and Standardize Username Constraints

### LINKED ISSUE #4809: [BUG]: User name length restriction is bogus
### How are you running AnythingLLM?

Docker (local)

### What happened?

User names here follow classic Unix conventions, which is initials. So just like it’s rm and ls and not remove and list, our users are called ag, dlm, daqb etc. depending on whether they have two, three or four initials. Even the admin user can’t be called admin, because usernames arbitrarily must have a length of six characters or more.
This seems to be an entirely bogus restriction that should be lifted.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by angelplusultra**
### Pull Request Type

- [ ] ✨ feat
- [ ] 🐛 fix
- [x] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #4809

### What is in this change?

This PR refactors username validation to use Unix-style constraints consistently across the entire application with proper internationalization support:

**Standardized Username Requirements:**
- Length: 2-32 characters (previously 2-100)
- Must start with a lowercase letter
- Can only contain: lowercase letters, numbers, underscores, hyphens, and periods
- Removed support for uppercase letters and special characters (@, %, +, -)

**Key Changes:**
1. **Centralized Validation Utility** - Created `frontend/src/utils/username.js` with:
   - Shared validation constants (`USERNAME_MIN_LENGTH`, `USERNAME_MAX_LENGTH`, `USERNAME_PATTERN`)
   - Unix-style regex pattern (`/^[a-z][a-z0-9._-]*$/`)
   - `validateUsername()` function for programmatic validation with detailed error messages

2. **Internationalization (i18n)** - Added localized username requirement strings:
   - `invite.username_requirements`
   - `admin.users.username_requirements`
   - `security.multiuser.enable.username_requirements`
   - Updated existing locale strings in `onboarding` and `account` sections

3. **Frontend Form Updates** - All user creation/edit forms now use:
   - Shared validation constants from utility file
   - HTML5 form validation attributes (`minLength`, `maxLength`, `pattern`)
   - Translated help text via `useTranslation()` hook
   - **Affected forms:**
     - Admin user creation/editing
     - Multi-user mode setup with client-side validation before submission
     - User onboarding flow with live validation
     - Account settings modal
     - Invite acceptance flow

4. **Backend Validation** - Updated `server/models/user.js`:
   - Aligned regex pattern with frontend Unix-style constraints
   - Enhanced `username` validation function to check regex pattern
   - Removed duplicate validation logic
   - Consistent error messages between frontend and backend

**Files Modified:**
- `frontend/src/utils/username.js` (new file)
- `frontend/src/locales/en/common.js`
- `frontend/src/components/UserMenu/AccountModal/index.jsx`
- `frontend/src/pages/Admin/Users/NewUserModal/index.jsx`
- `frontend/src/pages/Admin/Users/UserRow/EditUserModal/index.jsx`
- `frontend/src/pages/GeneralSettings/Security/index.jsx`
- `frontend/src/pages/Invite/NewUserModal/index.jsx`
- `frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx`
- `server/models/user.js`

### Additional Information

The translation normalization updates are included in #4832 

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

File: server/models/user.js [hunk 1]
```diff
@@ -167,16 +175,8 @@ const User = {
...
-        currentUser.username !== updates.username &&
-        !this.usernameRegex.test(updates.username)
-      )
-        return {
-          success: false,
-          error:
-            "Username must only contain letters, numbers, periods, underscores, hyphens, and email characters (@, %, +, -) with no spaces",
-        };
+      // Username validation is handled by the validations.username function
+      // which is called earlier in the update flow
```
Comment (timothycarambat) [inline server/models/user.js]: You can just delete this comment since you wont see the history if you revisit this in a yer

File: server/models/user.js [hunk 2]
```diff
@@ -13,7 +13,13 @@ const { EventLogs } = require("./eventLogs");
  */
 
 const User = {
-  usernameRegex: new RegExp(/^[a-zA-Z0-9._%+-@]+$/),
+  /**
```
Comment (timothycarambat) [inline server/models/user.js]: This comment should be moved to the validation since it described more than just the regex.

File: frontend/src/utils/username.js [hunk 3]
```diff
@@ -0,0 +1,52 @@
+/**
```
Comment (timothycarambat) [inline frontend/src/utils/username.js:1]: I can see the usefulness of this utility. It does feel like we should be only doing validations on the backend, though. This keeps the actual logic in a single place and the frontend is simply displaying the input with its known field restrictions.

This would be additional work though since we dont have an endpoint to do this and I wonder if that is even worth doing.

File: frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx [hunk 4]
```diff
@@ -291,7 +297,8 @@ const MyTeam = ({ setMultiUserLoginValid, myTeamSubmitRef, navigate }) => {
                   type="text"
                   className="border-none bg-theme-settings-input-bg text-white text-sm rounded-lg block w-full p-2.5 focus:outline-primary-button active:outline-primary-button placeholder:text-theme-text-secondary outline-none"
                   placeholder="Your admin username"
-                  minLength={6}
+                  minLength={USERNAME_MIN_LENGTH}
+                  maxLength={USERNAME_MAX_LENGTH}
```
Comment (timothycarambat) [inline frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx:298]: The button on onboarding does not enable until this validates, but if the pattern is wrong or something, there is no indication that the UI input is invalid. They would have to just assume it is an error with their input

File: frontend/src/locales/en/common.js [hunk 5]
```diff
@@ -697,6 +704,13 @@ const TRANSLATIONS = {
     },
   },
 
+  admin: {
+    users: {
+      username_requirements:
+        "Username must be 2-32 characters, start with a lowercase letter, and only contain lowercase letters, numbers, underscores, hyphens, and periods.",
+    },
+  },
+
```
Comment (timothycarambat) [inline frontend/src/locales/en/common.js]: You should move `username_requirements` to a child level key under `common`. It is the same string in every single place and will be annoying to support in so many places.

Comment (timothycarambat) [reply frontend/src/locales/en/common.js]: You will need to find every place and bump it to the common key across the UI to support this.

Comment (angelplusultra) [reply frontend/src/locales/en/common.js]: Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/ce9a3f0e04ec23b766dcd8f2eacbabb0658e7d68

File: frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx (hunk 4 above)
Comment (angelplusultra) [reply frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx:298]: How would you prefer to present feedback to the user? We could refactor the flow so that, instead of blocking onboarding progression until the username meets all conditions, users can attempt to submit their username and receive an error toast if it’s invalid and block them there. What do you think?

File: server/models/user.js (hunk 1 above)
Comment (angelplusultra) [reply server/models/user.js]: Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/20badb5cfd1f2319212e061d0e272dbfe87ae899

File: server/models/user.js (hunk 2 above)
Comment (angelplusultra) [reply server/models/user.js]: Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/20badb5cfd1f2319212e061d0e272dbfe87ae899

File: frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx (hunk 4 above)
Comment (angelplusultra) [reply frontend/src/pages/OnboardingFlow/Steps/UserSetup/index.jsx:298]: Consider chnages in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/e5b620404044f210375b3f715f5f7db7735f4118. Allows for the form to be sent to the server and if validation fails it presents a toast to the user.

File: frontend/src/utils/username.js (hunk 3 above)
Comment (angelplusultra) [reply frontend/src/utils/username.js:1]: Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/e5b620404044f210375b3f715f5f7db7735f4118. Removed validation in frontend.

**Comment by angelplusultra** [comment]
> We need some cleanup on some UI pages.
> ## Account modal
> 
> If i attempt to submit a bad name i get a generic "Internal server" error message in toast. It should surface the real error or enforce the pattern native HTML Validator message.
> 
> _this seems to be the only page showing a bad error message. All other UIs report the real error with an invalid username_


@timothycarambat Can you clarify what the "Account Modal" is? In `/settings/users` When I attempt to create a user in the modal after clicking "Add User" and input invalid data I get a clear error:

image


Same goes for the Edit User modal:

image

**Comment by timothycarambat** [comment]
> > We need some cleanup on some UI pages.
> > ## Account modal
> > If i attempt to submit a bad name i get a generic "Internal server" error message in toast. It should surface the real error or enforce the pattern native HTML Validator message.
> > _this seems to be the only page showing a bad error message. All other UIs report the real error with an invalid username_
> 
> @timothycarambat Can you clarify what the "Account Modal" is? In `/settings/users` When I attempt to create a user in the modal after clicking "Add User" and input invalid data I get a clear error:


Enable multi-user mode and click on the top-right user pfp icon to open the "settings" modal.

File: frontend/src/locales/en/common.js [hunk 6]
```diff
@@ -23,7 +23,7 @@ const TRANSLATIONS = {
 
       adminUsername: "Admin account username",
       adminUsernameReq:
-        "Username must be at least 6 characters long and only contain lowercase letters, numbers, underscores, and hyphens with no spaces.",
+        "Username must be 2-32 characters, start with a lowercase letter, and only contain lowercase letters, numbers, underscores, hyphens, and periods.",
```
Comment (timothycarambat) [inline frontend/src/locales/en/common.js]: You can remove and replace this tstring with `common.username_requirements`

File: frontend/src/locales/en/common.js [hunk 7]
```diff
@@ -989,7 +991,7 @@ const TRANSLATIONS = {
     remove_profile_picture: "Remove Profile Picture",
     username: "Username",
     username_description:
-      "Username must only contain lowercase letters, numbers, underscores, and hyphens with no spaces",
+      "Username must be 2-32 characters, start with a lowercase letter, and only contain lowercase letters, numbers, underscores, hyphens, and periods.",
```
Comment (timothycarambat) [inline frontend/src/locales/en/common.js]: Same here, can be using `common` string

**Comment by angelplusultra** [comment]
> > > We need some cleanup on some UI pages.
> > > ## Account modal
> > > If i attempt to submit a bad name i get a generic "Internal server" error message in toast. It should surface the real error or enforce the pattern native HTML Validator message.
> > > _this seems to be the only page showing a bad error message. All other UIs report the real error with an invalid username_
> > 
> > 
> > @timothycarambat Can you clarify what the "Account Modal" is? In `/settings/users` When I attempt to create a user in the modal after clicking "Add User" and input invalid data I get a clear error:
> 
> Enable multi-user mode and click on the top-right user pfp icon to open the "settings" modal.

Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/f8c1f029070ce6860ef0afcbf2be8318a76da216

File: frontend/src/locales/en/common.js (hunk 7 above)
Comment (angelplusultra) [reply frontend/src/locales/en/common.js]: Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/e3ffd5fda8b35ddf95db99a618d5738a0485d05d

File: frontend/src/locales/en/common.js (hunk 6 above)
Comment (angelplusultra) [reply frontend/src/locales/en/common.js]: Fix in https://github.com/Mintplex-Labs/anything-llm/pull/4828/commits/e3ffd5fda8b35ddf95db99a618d5738a0485d05d

**Comment by angelplusultra** [comment]
New Translations PR:

https://github.com/Mintplex-Labs/anything-llm/pull/4861
