### PR TITLE
Modify the PostgreSQL SQL connector to support querying tables from schemas other than the default public schema.

### LINKED ISSUE #4196: [FEAT]: Allow other schemas via Postgres SQL Connecter
### How are you running AnythingLLM?

Local development

### What happened?

The postgres sql connector is hardcoded to use the public schema. 
When generating queries it should append the schema name to the table e.g. schema.table

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by romanywu**
### Pull Request Type

- [x] ✨ feat
- [ ] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #4196 

### What is in this change?
Modify the PostgreSQL SQL connector to support querying tables from schemas other than the default public schema. The connector should dynamically include the schema name when generating SQL queries, using the schema.table format.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

File: server/utils/agents/aibitat/plugins/sql-agent/SQLConnectors/Postgresql.js [hunk 1]
```diff
@@ -54,10 +56,19 @@ class PostgresSQLConnector {
...
+
+  /**
+   * Returns the qualified table name with schema prefix
+   * @param {string} table_name - The table name
+   * @returns {string} - The qualified table name (schema.table)
+   */
+  getQualifiedTableName(table_name) {
+    return `${this.schema}.${table_name}`;
   }
 }
```
Comment (timothycarambat) [inline server/utils/agents/aibitat/plugins/sql-agent/SQLConnectors/Postgresql.js]: Please remove this function if it is unused anywhere - looks like it is not needed anywhere. Otherwise, works + LGTM

**Review by timothycarambat — DISMISSED** [review]
