### PR TITLE
Fix modal sizes to fit smaller screens & bug fixes

### LINKED ISSUE #396: Modal sizes too big in onboarding flow
Fix sizing of modals to fit on smaller screen sizes in onboarding flow.

### PR DESCRIPTION
**Pull request by shatfield4**
resolves #396 

- Adjusted padding and margin on all onboarding flow steps
- Fixed data handling step alignment
- Fix extra scrolling when viewing onboarding in mobile view
- Add message for mobile onboarding flor to use a desktop

### CODE REVIEW

File: frontend/src/pages/OnboardingFlow/OnboardingModal/Steps/DataHandling/index.jsx [hunk 1]
```diff
@@ -173,48 +173,51 @@ function DataHandling({ nextStep, prevStep, currentStep }) {
...
             {EMBEDDING_ENGINE_PRIVACY[embeddingEngine].description.map(
               (desc) => (
-                <li className="text-white/90 text-sm">{desc}</li>
+                <p className="text-white/90 text-sm">
+                  <b>•</b> {desc}
+                </p>
               )
             )}
-          </ul>
+          </div>
```
Comment (timothycarambat) [inline frontend/src/pages/OnboardingFlow/OnboardingModal/Steps/DataHandling/index.jsx:196]: Why cant we just keep using a `<ul>` here with `list-disc` which will add the dots for us?

File: frontend/src/pages/OnboardingFlow/OnboardingModal/Steps/DataHandling/index.jsx [hunk 2]
```diff
@@ -173,48 +173,51 @@ function DataHandling({ nextStep, prevStep, currentStep }) {
...
-          <ul className="flex flex-col list-disc">
+          <div className="flex flex-col">
             {VECTOR_DB_PRIVACY[vectorDb].description.map((desc) => (
-              <li className="text-white/90 text-sm">{desc}</li>
+              <p className="text-white/90 text-sm">
+                <b>•</b> {desc}
+              </p>
             ))}
-          </ul>
+          </div>
```
Comment (timothycarambat) [inline frontend/src/pages/OnboardingFlow/OnboardingModal/Steps/DataHandling/index.jsx:217]: Same here

**Review by timothycarambat — CHANGES_REQUESTED** [review]
