### PR TITLE
Fix white screen bug when deleting chats under Workspace Chats menu

### LINKED ISSUE #669: [BUG]: White screen after deleting a workspace chat from settings
### How are you running AnythingLLM?

Local development

### What happened?

When you are at the page "Workspace Chats", and you have more than one
page of chats, and you delete a chat, and then use the button "next
page" or "previous page", the app crashes with a white screen.
Restarting the app shows that the chat(s) was/were deleted.

### Are there known steps to reproduce?

This only happens when there are more than 20 chats sent and we see the next and previous pages for pagination.

### PR DESCRIPTION
**Pull request by shatfield4**
… on delete/fix backend invalid json error

 ### Pull Request Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #669 

### What is in this change?

Describe the changes in this PR that are impactful to the repo.

- Fix a bug where if we have more than 20 workspace chats and we delete a chat then click previous or next buttons, a white screen would show until we refresh the page
- Changed from using a ref to delete the row to just filtering out the chats in the parent component

### Additional Information

Add any other context about the Pull Request here that was not captured above.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

File: server/endpoints/system.js [hunk 1]
```diff
@@ -774,7 +774,7 @@ function systemEndpoints(app) {
       try {
         const { id } = request.params;
         await WorkspaceChats.delete({ id: Number(id) });
-        response.sendStatus(200).end();
+        response.json({ success: true });
```
Comment (timothycarambat) [inline server/endpoints/system.js:777]: Why change this if we dont use it on the frontend?

File: frontend/src/pages/GeneralSettings/Chats/index.jsx [hunk 2]
```diff
@@ -142,6 +142,10 @@ function ChatsContainer() {
     setOffset(offset + 1);
   };
 
+  const handleDeleteChat = (chatId) => {
+    setChats((prevChats) => prevChats.filter((chat) => chat.id !== chatId));
+  };
```
Comment (timothycarambat) [inline frontend/src/pages/GeneralSettings/Chats/index.jsx:147]: 👍 makes sense, the max this list can even be is 20 anyway
