### PR TITLE
[FIX] Add max tokens field to generic OpenAI LLM connector

### LINKED ISSUE #1342: [FEAT]: Be able to set max tokens generated in LLM setup
### What would you like to see?

In the Generic OpenI - Unfortunately im dealing with an endpoint with a default max tokens of 16 but I need to increase that manually to something like 1024.

### PR DESCRIPTION
**Pull request by shatfield4**
### Pull Request Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #1342 

### What is in this change?

- Add max tokens field to generic OpenAI LLM connector to allow for more control over responses

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x]  Docker build succeeds locally

### CODE REVIEW

File: server/utils/AiProviders/genericOpenAi/index.js [hunk 1]
```diff
@@ -94,6 +95,7 @@ class GenericOpenAiLLM {
         model: this.model,
         messages,
         temperature,
+        max_tokens: this.maxTokens,
```
Comment (timothycarambat) [inline server/utils/AiProviders/genericOpenAi/index.js:98]: We need to spread this property to the `agents` Integration as well to ensure that it wont get blocked by low `max_token` responses as well

**Review by timothycarambat — CHANGES_REQUESTED** [review]
Everything else looks good, lets just get this into agent integration as well

**Review by timothycarambat — APPROVED** [review]
