### PR TITLE
fix truncate function to handle Chinese characters

### LINKED ISSUE #671: [BUG]:  When the file name is too long, the date information will be overwritten.
### How are you running AnythingLLM?

Local development

### What happened?

 When the file name is too long, the date information will be overwritten.

image

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by shatfield4**
### Pull Request Type

- [ ] ✨ feat
- [x] 🐛 fix
- [ ] ♻️ refactor
- [ ] 💄 style
- [ ] 🔨 chore
- [ ] 📝 docs

### Relevant Issues

resolves #671 

### What is in this change?

Describe the changes in this PR that are impactful to the repo.

- Resolve issue with Chinese characters not being truncated properly in the document picker

### Additional Information

Add any other context about the Pull Request here that was not captured above.

### Developer Validations

- [x] I ran `yarn lint` from the root of the repo & committed changes
- [x] Relevant documentation has been updated
- [x] I have tested my code functionality
- [x] Docker build succeeds locally

### CODE REVIEW

File: frontend/src/utils/directories.js [hunk 1]
```diff
@@ -12,22 +12,27 @@ export function getFileExtension(path) {
...
+    ? startLength - Math.ceil(extension.length / 2)
+    : startLength;
+  const adjustedEndLength = extension
+    ? endLength - Math.floor(extension.length / 2)
+    : endLength;
+  const truncated =
+    nameWithoutExtension.substr(0, adjustedStartLength) +
+    "..." +
+    nameWithoutExtension.slice(-adjustedEndLength);
+  return truncated + extension;
```
Comment (timothycarambat) [inline frontend/src/utils/directories.js:37]: Im gonna be honest I cannot easily tell what is going on here. What is happening in this code and what are the match operations being done. What is `-3` in the `n-3` operations?

Comment (timothycarambat) [reply frontend/src/utils/directories.js:37]: If possible we should just try to solve this issue without touching this function if possible. Either via CSS or otherwise.

**Review by timothycarambat — CHANGES_REQUESTED** [review]

File: frontend/src/utils/directories.js (hunk 1 above)
Comment (shatfield4) [reply frontend/src/utils/directories.js:37]: The `+ and - 3` are to account for the `...`

- Noted, will solve using CSS instead then

**Review by timothycarambat — APPROVED** [review]
